## Assignment 3

### Task 1

1. Write a function to compute 5/0 and use try/except to catch the exceptions

In [4]:
try:
    5/0
except ArithmeticError as e:
    print('Error:' ,e)

Error: division by zero


#### 2. 
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.
    
- subjects=["Americans ","Indians"]
- verbs=["play","watch"]
- objects=["Baseball","Cricket"]

In [5]:
subjects =["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i  in subjects:
    for j in verbs:
        for k in objects:
            print (i+' '+j+' '+k+'.')

#alternate

#[[i,j,k] for i in subjects for j in verbs for k in objects]

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


### Task 2

1. Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde

In [11]:
import numpy as np
def gen_vander_matrix(ipvector, n, increasing=False):
    
    if increasing == False:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing == True:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

In [12]:
inputvector = np.array([1,2,3,4,5])

op_matx_dec_order = gen_vander_matrix(inputvector,4,False)
op_matx_inc_order = gen_vander_matrix(inputvector,4,True)

print("The input array is:",inputvector,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

The input array is: [1 2 3 4 5] 

Vander matrix of the input array in decreasing order of powers:

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]] 

